wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=fddqs32
    ports:
     - "8000:80"
    volumes:
     - ./code:/code
     - ./wordpress:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=fddqs32
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql